language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

# command to run tests
script:
  python -W all runtests.py --with-coverage --cover-html --cover-html-dir=Coverage_report

after_success:
  - codecov

before_deploy:
  # Generate source distribution.
  # Note: only do this with Python 3.5 because the contents
  # of the distribution are the same for all versions.
  - case "$TRAVIS_PYTHON_VERSION" in 3.5) python setup.py sdist --formats=bztar;; esac
  # Generate wheel distribution.
  # Note: only do this once, since we create a universal wheel.
  - case "$TRAVIS_PYTHON_VERSION" in 3.5) python setup.py bdist_wheel;; esac

deploy:
  - provider: releases
    api_key:
      secure: "kZHDE09hKehX8bFRWa5qM56J3ujc3Stl5j2u9KfdXwmZyYlremZTJ5J9gdiLqqRrTI1jF5n+3miacYSdups1VSqgXYsGzoz99HurtcoMfkFxWkkeCnd6ORwvTXYFN28t2CcjWXV6jCyUABPaEv8TCK3/+LeFfuf30O5Hxg/KiUfpqBwXj6sWaht0whhay45r6D5nYb8omhqa7n4DDLlrStRqkp1SB895EElessFFuHjn/jkxlyEUjGjQ+x79h8JKiXVozYRcyb4eC75xIaE6+yeA6q2ZxMrNRdBnWbRrFBNYsx4QbMCe9vq2m0IQMkrh0kk5N53eA6/8Yy6ZpDUNAb/Alvql8+y/qWwVQl3TYwcMGd0PctmfGH6rElByiOIVV9Zv52hTK9jXky0ab+avLufXlL8tUDVSNReXR7En37vbxlq+AU+xNhHN3girkJJ7jU6saQpj1tROGBpPkLIIHQFh3dbubfgw9qdW5qYBZyLHK9yKNnlzFIr7yktqJvJ/jGz/YDER12UdlCzaoWtVdw8Ogm9faAFlMUvzExYt5BIneDYUe13GtoDw69aLiuq5YGcFKClsgDIqBqYYBTVIHwAS9kTV4CZV0L4C15ylmUIP68LFxZ/stufXW0MJxvhIaJ7gJ9d9LyCK1a0u0j5a78cX/OUx9RfqjOMCuVbGTys="
    file_glob: true
    file:
    - dist/*.tar.*
    - dist/*.whl
    on:
      tags: true
    skip_cleanup: true
